TER-28: Enable universal line mode on `az .run()`  and get a string as output instead of binary
that fixes the exception:
```
Traceback (most recent call last):
  File "/mnt/c/Users/shreps/Repos/havas.terraform.azure/.wrapper/bin/tfwrapper", line 604, in <module>
    main()
  File "/mnt/c/Users/shreps/Repos/havas.terraform.azure/.wrapper/bin/tfwrapper", line 554, in main
    az_token = json.loads(result_json)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```